CREATE DATABASE IF NOT EXISTS sistem_kasir CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sistem_kasir;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100) NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('admin','kasir') NOT NULL DEFAULT 'kasir',
  aktif TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS barang (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  id_barang VARCHAR(50) NOT NULL UNIQUE,
  nama VARCHAR(150) NOT NULL,
  merek VARCHAR(100) DEFAULT '',
  harga BIGINT UNSIGNED NOT NULL DEFAULT 0,
  aktif TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS stok (
  barang_id INT UNSIGNED PRIMARY KEY,
  stok_gudang INT UNSIGNED NOT NULL DEFAULT 0,
  stok_etalase INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_stok_barang FOREIGN KEY (barang_id) REFERENCES barang(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS transaksi (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  kode_transaksi VARCHAR(40) NOT NULL UNIQUE,
  user_id INT UNSIGNED NOT NULL,
  total BIGINT UNSIGNED NOT NULL,
  bayar BIGINT UNSIGNED NOT NULL,
  kembalian BIGINT UNSIGNED NOT NULL,
  status ENUM('selesai','batal') NOT NULL DEFAULT 'selesai',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_transaksi_user FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  INDEX idx_transaksi_tanggal (created_at),
  INDEX idx_transaksi_user (user_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS detail_transaksi (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  transaksi_id BIGINT UNSIGNED NOT NULL,
  barang_id INT UNSIGNED NOT NULL,
  nama_barang VARCHAR(150) NOT NULL,
  harga BIGINT UNSIGNED NOT NULL,
  qty INT UNSIGNED NOT NULL,
  subtotal BIGINT UNSIGNED NOT NULL,
  CONSTRAINT fk_detail_transaksi FOREIGN KEY (transaksi_id) REFERENCES transaksi(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_detail_barang FOREIGN KEY (barang_id) REFERENCES barang(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  INDEX idx_detail_transaksi (transaksi_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS riwayat_stok (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  barang_id INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  lokasi ENUM('gudang','etalase') NOT NULL,
  jenis ENUM('masuk','keluar') NOT NULL,
  jumlah INT UNSIGNED NOT NULL,
  catatan VARCHAR(255) DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_riwayat_barang FOREIGN KEY (barang_id) REFERENCES barang(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_riwayat_user FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  INDEX idx_riwayat_tanggal (created_at)
) ENGINE=InnoDB;

-- Akun admin awal dibuat dengan tools/setup_admin.php setelah impor database.
